### ISSUE TITLE
Turning effect blocks on/off on the MS-50G

### ISSUE THREAD

**Issue by Combustao** [shooking/ZoomPedalFun#37]
I have a Zoom MS-50G and I always found it strange that it is not possible to turn on/off all 6 blocks of the preset signal chain using MIDI commands.

The code "F0 52 00 58 31 bb 00 xx 00 F7", where bb corresponds to the block (1st = 00, 2nd = 01 and 3rd = 02) and xx corresponds to the on/off action (on = 01 and off = 00) acts on the MS-50G in the first 3 blocks, but if I follow the same logic for the following blocks, with bb = 03, 04 and 05, nothing happens on the Zoom.

I have already connected the MS-50G to the computer and through MIDI OX I even saw that when I turn on/off the 4th, 5th or 6th effect block this same MIDI code is sent to MIDI OX, but when I try to do the opposite, that is, MIDI OX sending the command to the MS-50G nothing happens.

Does anyone know why this happens or how to resolve this situation?

**Comment by shooking** [comment]
I believe this is a known bug in the older pedals. Zoom won't fix it.
The only workaround I know is to read the whole patch in then update and write it back.

There might be a way to rotate the FX around (you can do this on the later pedals - see my wiki for and example).
So one can on modern pedals swap 6 with 1 says, turn it on off, swap it back. But I don't recall if this midi command exists on the older ones.

**Comment by nomadbyte** [comment]
> ...Does anyone know why this happens or how to resolve this situation?

To me this seems more like a mix-up with the MS-60B specs, which supports only up to 4 effects. Someplace in firmware code there's a hard coded 4 (or to the effect of it) instead of the parameter for the max number of supported effects in patch chain. Possibly, it's in the processing of the received SysEx messages.

Because there's no official editor for the multistomps (other than StompShare app for MS-100BT), this "bug" never got exposed. Also, sending the whole updated patch is just as easy on changes like that.

Given that multistomps only have one direct On/Off indicator, the indirect changes for non-current effect cannot be visible, so, indeed, changing them "undercover" may not be the best choice vs. explicit loading of a new patch. On G1 FOUR, for example, each effect in the chain has its own indicator button.

Anyway, it's easier to just create a __different patch__ with the wanted effects or On/Off state and chain it using A-B or just load it with MIDI CC message.

**Comment by shooking** [comment]
Closing - I suspect, as ever, @nomadbyte is correct.
It would be so great if Zoom opened up the firmware for these beasts.
There again I am making decent progress with the ti-6000 tools.
